version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

  app:
    build: .
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_master
      - DB_READ_HOST=mysql_slave
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
    volumes:
      - storage:/var/www/storage
      - bootstrap_cache:/var/www/bootstrap/cache
    depends_on:
      - mysql_master
      - redis
    restart: unless-stopped
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  queue_worker:
    build: .
    command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --memory=512
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_master
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - storage:/var/www/storage
    depends_on:
      - mysql_master
      - redis
    restart: unless-stopped
    deploy:
      replicas: 5
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  schedule_runner:
    build: .
    command: >
      sh -c "while true; do
        php artisan schedule:run
        sleep 60
      done"
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_master
      - REDIS_HOST=redis
    volumes:
      - storage:/var/www/storage
    depends_on:
      - mysql_master
      - redis
    restart: unless-stopped

  mysql_master:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: >
      --innodb-buffer-pool-size=2G
      --innodb-log-file-size=256M
      --max-connections=300
      --query-cache-type=1
      --query-cache-size=256M
      --slow-query-log=1
      --log-queries-not-using-indexes=1
    volumes:
      - mysql_master_data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mysql_slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: >
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=128M
      --max-connections=200
      --read-only=1
    volumes:
      - mysql_slave_data:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    image: redis:7-alpine
    command: >
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G

  redis_cache:
    image: redis:7-alpine
    command: >
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    restart: unless-stopped

volumes:
  mysql_master_data:
  mysql_slave_data:
  redis_data:
  storage:
  bootstrap_cache: 